- name: Set up MongoDB backup to GCS bucket
  hosts: mongodbgroup
  become: yes
  gather_facts: no

  vars:
    gcs_bucket: "clgcporg10-190-db-backup"
    backup_script_path: "/usr/local/bin/backup_mongo_to_gcs.sh"

  tasks:

    - name: Install required packages (fallback raw mode)
      raw: |
        apt-get update && \
        apt-get install -y mongodb-clients google-cloud-sdk cron

    - name: Create MongoDB backup script
      copy:
        dest: "{{ backup_script_path }}"
        mode: '0755'
        content: |
          #!/bin/bash
          DATE=$(date +%F-%H-%M)
          BACKUP_DIR="/tmp/mongo-backup-$DATE"
          ARCHIVE="$BACKUP_DIR.tar.gz"
          BUCKET="gs://{{ gcs_bucket }}"

          # Create backup
          mongodump --out "$BACKUP_DIR"

          # Compress it
          tar -czf "$ARCHIVE" -C /tmp "mongo-backup-$DATE"

          # Upload to GCS
          gsutil cp "$ARCHIVE" "$BUCKET"

          # Clean up
          rm -rf "$BACKUP_DIR" "$ARCHIVE"

    - name: Add cron job for daily MongoDB backup at 2 AM
      cron:
        name: "Daily MongoDB backup to GCS"
        job: "{{ backup_script_path }} >> /var/log/mongo_backup.log 2>&1"
        minute: "0"
        hour: "2"
