name: Deploy terraform to clgcporg10-190

on:
  workflow_dispatch:
  push:
    branches:
      - main
jobs:
  apply:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Authenticate to GCP
        uses: google-github-actions/auth@v2
        with:
          credentials_json: ${{ secrets.GCP_SA_KEY }}

      - name: Set up gcloud CLI
        uses: google-github-actions/setup-gcloud@v2

      - name: Install Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.12.0

      - name: Terraform Init
        working-directory: terraform
        run: terraform init -reconfigure


      - name: Terraform Plan
        working-directory: terraform
        run: |
          terraform plan

      - name: Terraform Apply
        if: github.ref == 'refs/heads/main'
        working-directory: terraform
        run: |
          terraform apply -auto-approve

      - name: Get GKE credentials
        uses: google-github-actions/get-gke-credentials@v2
        with:
          cluster_name: cluster-for-evgenii-app
          location: europe-west1
          project_id: clgcporg10-190

      - name: Deploy to Kubernetes
        working-directory: kubernetes
        run: |
          kubectl apply -f kubernetes_app_admin_sa.yaml
          kubectl apply -f kubernetes_cluster_role.yaml
          kubectl apply -f kubernetes_deployment.yaml
          kubectl apply -f kubernetes_service.yaml
          kubectl apply -f kubernetes_app_admin_sa_secret.yaml
          

      - name: Install Ansible 2.9
        run: |
          sudo apt-get update
          sudo apt-get install -y python3-pip python3-setuptools
          pip3 install ansible==2.9


      - name: Run Ansible Playbook
        working-directory: ansible
        env:
          ANSIBLE_HOST_KEY_CHECKING: "False"
        run: |
          echo "${{ secrets.ANSIBLE_SSH_PRIVATE_KEY }}" > ansible_key.pem
          chmod 600 ansible_key.pem
          export ANSIBLE_PRIVATE_KEY_FILE=ansible_key.pem
          ansible-playbook -i inventory backup_mongo.yaml --private-key=ansible_key.pem -u evgeniikosarev